# Site settings
title: Ian Renton
email: ian@ianrenton.com
tagline: Software engineer and builder of robots
description: The website of Ian Renton, a software engineer and builder of robots
baseurl: ""
url: "https://ianrenton.com"
author: Ian Renton
lang: en-GB
future: true

# Build settings
#lsi: false
#safe: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
auto_ids: true
sass:
  style: compressed
plugins: [jekyll-sitemap, jekyll-redirect-from, jekyll-seo-tag, jekyll-feed]
permalink: /:categories/:title/
include: [".well-known"]

# Staticman
staticman_url: https://staticman.ianrenton.com/v3/entry/github/ianrenton/ianrenton.com/master/comments
repository  : "ianrenton/ianrenton.com"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
reCaptcha:
  # the siteKey is used as-is (no encryption)
  siteKey: 6LeG1LwSAAAAADsQfXoCfeTCH6JuxAGyImxoIjux
  # the secret is the encrypted blob you got back from the encrypt call
  secret: AxIRxnDMdqKobFt/xhkYtejh1L+U3249syxVtZPYZnGAHqIsK0Tjv3XTaU+keINV1nzr/Bw/FxmztMy1XbXV31c5NFPvOnAmgiJfZyBOWyOQQ5GvQRvC/coNLJ7bOiMykC3vlW0IVP7cwpjEokxWa8wCkhJ9pf1WzioO+nQTvsRVYYbaptxBYY0+ag664nj0j+9+Rm+EfW7GuXLtq7hPJsP7xcndbKdj3h26Iu/QBrXPPDtsBY18KJShk+OPVBwQtYnT0lZWfhmRI3kCZ4I2c7qAHNZZuZrkmASF5KzoE6GeBFnZrG8mjZVgnYFUad9kqqBqPoJfbW0mOAdaK06pkGrnFuTg2BZkv56UNIW3u9TyMxeOE2MXYGp6YiLzDtgmQljKy0qESaQed1sjqwbt7mqSMQZihEEW5mUYqhMUoIH/2GJo+DwxMyQwLTlKVd5FRTjSS40y5mLcNhG/+ni6EhxHCGecX7biUEMQsjvQBhUtgBMIX8HUJNv4o1sbfMj7WqHIsNLnTkmUyLGhv7guaVsZ1DYBAdhP2i8c0kaMAmHjJTAEKZ4Rl/z4A/ZMmBOvHJWj2IqSCk0/1R0FxLMCMZ9nwKBDjMqxKhO+Es5YprbSffA4ixnWT+3hFrZP0RwKVFVSEBWi2FTCH6WZViWsR0vSNaxrkvDn5Jd+HAbHG7Q=

# Category friendly names. We use file paths as post categories so they are strings like "filmreviews" and
# "planesailing", but when displaying them in the browser we want to convert them to e.g. "Film Reviews"
# and "Plane/Sailing" to match the titles of the category index pages.
categoryFriendlyNames:
  atp: "All-Terrain Pi"
  big-mouth-phatt-bass: "Big Mouth Phatt Bass"
  bluetooth-bass: "Billy Bass Sat Nav / Bluetooth Bass"
  blog: "Blog"
  characters: "Characters"
  fiction: "Fiction"
  filmreviews: "Film Reviews"
  lego-turtle: "Lego Turtle"
  planesailing: "Plane/Sailing"
  planesailing-portable: "Plane/Sailing Portable"
  quadcopter: "Quadcopter"
  radioshack: "Radio Shack"
  raspberry-tank: "Raspberry Tank"
  rpgs: "RPGs"
  usv-01: "USV-01 Harry Paye"

  