# Site settings
title: Ian Renton
email: ian@ianrenton.com
tagline: Software engineer and builder of robots
description: The website of Ian Renton, a software engineer and builder of robots
baseurl: ""
url: "https://ianrenton.com"
lang: en_GB
future: true

# SEO plugin
social:
  name: Ian Renton
  links:
    - https://twitter.com/i_renton
    - https://github.com/ianrenton
twitter:
  username: i_renton

# Build settings
#lsi: false
#safe: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
auto_ids: true
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from, jekyll-seo-tag]
permalink: /blog/:title/

# Staticman
staticman_url: https://ianrentoncom-staticman.herokuapp.com/v2/entry/ianrenton/ianrenton.com/master/comments
repository  : "ianrenton/ianrenton.com"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
reCaptcha:
  # the siteKey is used as-is (no encryption)
  siteKey: 6LeG1LwSAAAAADsQfXoCfeTCH6JuxAGyImxoIjux
  # the secret is the encrypted blob you got back from the encrypt call
  secret: IsYxi/A4zrs0bFV7/0j3QCsJaFbiW3++9m12lOL7HdW+deMeislTpiwNm30kgfX40frUv1hUXciwMD+HE4j2BQvXtCHnWcRspFwYi19D5iN2niBa3JMAvsEx2m1D2pQ5ZPynjjDUeMzKMRlSn68KguQC95wfnewCduhwohn6v23HHw3zFakdhKHFfmGByB2jddsIJ5/OTnfUuwX6/FOc85j+0pDRxnPCEliWDOGnqWps1Qr+UnkNHcwwtvI81O85QfqWwg0IU0uolAonJ3dKKClvdcUQ+gCXu/HSGza/i4RsmWKNYZRo8aGk5l9X0iKQyokawm1aZUa6RIXIawItu0rD1CGTYDgKhcbHpI5fTu3CxhtGtjURz8BLKQSd4bwgmDd4uyX+z8uXdg3O4pTCL3sh9oduOMeZSltefiGdbtYvGNtY6aVW4dCK2tHkjBgn0AiCpvkFvuV3p4VE9zyZgpxMD+u/Lu+F/Zl4HiZfOsqQzgwyMOmB06eyLKNPd4oygMvkWdtne3uGDwZlZhtMdPcPRHm8Nv+PmP8ur0unTdZ0BTAtLvrPNBhStq+SHNBBYJ6FrEV5+Ggn4BZQN81fbACuutvqV3NEdDgfaXx0F/JCr0JFcOIqKcxnPYzCLyQDSYC00pa6wlr4G5Rie9GNr8Vx5vFUE1M2Lh/YZZn0sWc=

# Collections
collections:
  fiction:
    output: true
    permalink: /fiction/:title/
    collectiontitle: Stories & Fiction
    collectionindex: /fiction/
    showprevnext: false
  characters:
    output: true
    permalink: /fiction/characters/:title/
    collectiontitle: Characters
    collectionindex: /fiction/characters/
    showprevnext: false
  filmreviews:
    output: true
    permalink: /filmreviews/:title/
    collectiontitle: Film Review by the Numbers
    collectionindex: /filmreviews/
    showprevnext: true
  guides:
    output: true
    permalink: /guides/:title/
    collectiontitle: Guide
    collectionindex: /guides/
    showprevnext: false
  recipes:
    output: true
    permalink: /recipes/:title/
    collectiontitle: Recipe
    collectionindex: /recipes/
    showprevnext: false
  rpgs:
    output: true
    permalink: /rpgs/:title/
    collectiontitle: Roleplaying Games
    collectionindex: /rpgs/
    showprevnext: false
  software:
    output: true
    permalink: /software/:title/
    collectiontitle: Software
    collectionindex: /software/
    showprevnext: false
  hardware:
    output: true
    permalink: /hardware/:title/
    collectiontitle: Hardware
    collectionindex: /hardware/
    showprevnext: true
  raspberrytank:
    output: true
    permalink: /hardware/raspberry-tank/:title/
    collectiontitle: Raspberry Tank
    collectionindex: /hardware/raspberry-tank/
    showprevnext: true
  quadcopter:
    output: true
    permalink: /hardware/quadcopter/:title/
    collectiontitle: Quadcopter
    collectionindex: /hardware/quadcopter/
    showprevnext: true
  usv01:
    output: true
    permalink: /hardware/usv-01/:title/
    collectiontitle: USV-01 "Harry Paye"
    collectionindex: /hardware/usv-01/
    showprevnext: true
  atp:
    output: true
    permalink: /hardware/atp/:title/
    collectiontitle: All-Terrain Pi
    collectionindex: /hardware/atp/
    showprevnext: true
  legoturtle:
    output: true
    permalink: /hardware/lego-turtle/:title/
    collectiontitle: Lego Turtle
    collectionindex: /hardware/lego-turtle/
    showprevnext: true
  planesailing:
    output: true
    permalink: /hardware/planesailing/:title/
    collectiontitle: Plane/Sailing
    collectionindex: /hardware/planesailing/
    showprevnext: true
  radioshack:
    output: true
    permalink: /hardware/radioshack/:title/
    collectiontitle: Radio Shack
    collectionindex: /hardware/radioshack/
    showprevnext: false

# jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

# Category & Year archives for the blog posts
#jekyll-archives:
#  enabled:
#  - year
#  - categories
#  layouts:
#    year: archive-year
#    category: archive-category
#  permalinks:
#    year: '/blog/:year/'
#    category: '/blog/category/:name/'
