# Site settings
title: Ian's Blog
email: ian@ianrenton.com
description: Coffee goes in, words come out.
baseurl: ""
url: "https://ianrenton.com" # the base hostname & protocol for your site

# Build settings
#lsi: false
#safe: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  style: compressed
gems: [jekyll-paginate, jekyll-archives]
permalink: /blog/:title/

# Juvia
juvia_site_key: jei5gff5948ceh4w90b0hvnsfor7841
juvia_host: juvia.ianrenton.com
juvia_comment_order: earliest-first

# Collections
collections:
  fiction:
    output: true
    permalink: /fiction/:title/
    collectiontitle: Stories & Fiction
    collectionindex: /fiction/
    showprevnext: false
  characters:
    output: true
    permalink: /fiction/characters/:title/
    collectiontitle: Characters
    collectionindex: /fiction/characters/
    showprevnext: false
  filmreviews:
    output: true
    permalink: /filmreviews/:title/
    collectiontitle: Film Review by the Numbers
    collectionindex: /filmreviews/
    showprevnext: true
  guides:
    output: true
    permalink: /guides/:title/
    collectiontitle: Guide
    collectionindex: /guides/
    showprevnext: false
  recipes:
    output: true
    permalink: /recipes/:title/
    collectiontitle: Recipe
    collectionindex: /recipes/
    showprevnext: false
  rpgs:
    output: true
    permalink: /rpgs/:title/
    collectiontitle: Roleplaying Games
    collectionindex: /rpgs/
    showprevnext: false
  software:
    output: true
    permalink: /software/:title/
    collectiontitle: Software
    collectionindex: /software/
    showprevnext: false
  hardware:
    output: true
    permalink: /hardware/:title/
    collectiontitle: Hardware
    collectionindex: /hardware/
    showprevnext: true
  raspberrytank:
    output: true
    permalink: /hardware/raspberry-tank/:title/
    collectiontitle: Raspberry Tank
    collectionindex: /hardware/raspberry-tank/
    showprevnext: true
  quadcopter:
    output: true
    permalink: /hardware/quadcopter/:title/
    collectiontitle: Quadcopter
    collectionindex: /hardware/quadcopter/
    showprevnext: true
  usv01:
    output: true
    permalink: /hardware/usv-01/:title/
    collectiontitle: USV-01 "Harry Paye"
    collectionindex: /hardware/usv-01/
    showprevnext: true
  atp:
    output: true
    permalink: /hardware/atp/:title/
    collectiontitle: All-Terrain Pi
    collectionindex: /hardware/atp/
    showprevnext: true
  legoturtle:
    output: true
    permalink: /hardware/lego-turtle/:title/
    collectiontitle: Lego Turtle
    collectionindex: /hardware/lego-turtle/
    showprevnext: true

paginate: 10
paginate_path: "/blog/page:num/"

# Category & Year archives for the blog posts
jekyll-archives:
  enabled:
  - year
#  - categories
  layouts:
    year: archive-year
#    category: archive-category
  permalinks:
    year: '/blog/:year/'
#    category: '/blog/category/:name/'
