# Site settings
title: Ian's Blog
email: ian@ianrenton.com
description: Coffee goes in, words come out.
baseurl: ""
url: "https://ianrenton.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: [octopress-image-tag, octopress-quote-tag, octopress-codeblock, octopress-codefence, octopress-paginate, jekyll-sitemap, jekyll-archives]
permalink: /blog/:title/

# Juvia
juvia_site_key: jei5gff5948ceh4w90b0hvnsfor7841
juvia_host: juvia.ianrenton.com
juvia_comment_order: earliest-first

# Tag all posts with a property for easy checking
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Collections
collections:
  fiction:
    output: true
    permalink: /fiction/:title/
  filmreviews:
    output: true
    permalink: /filmreviews/:title/
  guides:
    output: true
    permalink: /guides/:title/
  recipes:
    output: true
    permalink: /recipes/:title/
  rpgs:
    output: true
    permalink: /rpgs/:title/
  software:
    output: true
    permalink: /software/:title/
  hardware:
    output: true
    permalink: /hardware/:title/
    
pagination:
  limit: false
  permalink: /page/:num/
  
# Category & Year archives for the blog posts
jekyll-archives:
  enabled:
  - year
  - categories
  layouts:
    year: archive-year
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    category: '/blog/category/:name/'
